query ($timestamp_start: Int!, $timestamp_end: Int!) {
  burnedBFRs(
    first: 1000
    orderBy: timestamp
    orderDirection: desc
    where: { period: daily, timestamp_gte: $timestamp_start, timestamp_lte: $timestamp_end }
    subgraphError: allow
  ) {
    timestamp
    amount
  }
}
