query ($timestamp_start: Int!, $timestamp_end: Int!) {
  poolStatsAllTime: poolStats(
    orderBy: timestamp
    orderDirection: desc
    where: { period: daily }
    subgraphError: allow
  ) {
    timestamp
    amount
    period
    timestamp
    rate
    id
  }
  poolStats(
    orderBy: timestamp
    orderDirection: desc
    where: { period: daily, timestamp_gte: $timestamp_start, timestamp_lte: $timestamp_end }
    subgraphError: allow
  ) {
    timestamp
    amount
    period
    timestamp
    rate
    id
  }
}
