query ($address: String!, $timestamp: String!, $timestampReward: String!) {
  userStats: weeklyLeaderboards(
    orderBy: netPnL
    orderDirection: desc
    first: 100
    where: {
      timestamp: $timestamp
      totalTrades_gte: 5
      user_not_in: [
        "0x361e9013d7e4f2e4a035ba97fdb42cb7d2540259"
        "0x6fae0eed696ec28c81269b99240ee960570666f1"
        "0x0b8750c12fa14decd31eadff7e92cbd64a198094"
        "0x10df9a95010c8b9fbdc8f6191de824df9c99a8d8"
        "0x547a821c692921d82ebd936320dc1a608a6e38c1"
        "0x2a007f31146ff8f939b6ca3ad18c8d2a6e42eb73"
        "0xf0344cc4e0c0b5e653a83e4e2c9cb198cb8bf60d"
        "0x7d74c85df27fc42142ada6a238411727ee5572e0"
        "0x38126b14fb81c50b58a00ebfd8376f5e3de82438"
        "0xf5996dd3efc0ba3cf664209db59e441c34758de7"
        "0xa506565e7d1330f172ba41aaf90b840c47a0b822"
        "0xba60ec5b1c28993cba0e1c5022dc4c4735718873"
      ]
    }
  ) {
    user
    totalTrades
    netPnL
    volume
    usdcNetPnL
    usdcTotalTrades
    usdcTradesWon
    usdcVolume
    usdcWinRate
    # bfrNetPnL
    # bfrTotalTrades
    # bfrTradesWon
    # bfrVolume
    # bfrWinRate
    # arbNetPnL
    # arbTotalTrades
    # arbTradesWon
    # arbVolume
    # arbWinRate
  }
  loserStats: weeklyLeaderboards(
    orderBy: netPnL
    orderDirection: asc
    first: 100
    where: {
      timestamp: $timestamp
      totalTrades_gte: 5
      user_not_in: [
        "0x361e9013d7e4f2e4a035ba97fdb42cb7d2540259"
        "0x6fae0eed696ec28c81269b99240ee960570666f1"
        "0x0b8750c12fa14decd31eadff7e92cbd64a198094"
        "0x10df9a95010c8b9fbdc8f6191de824df9c99a8d8"
        "0x547a821c692921d82ebd936320dc1a608a6e38c1"
        "0x2a007f31146ff8f939b6ca3ad18c8d2a6e42eb73"
        "0xf0344cc4e0c0b5e653a83e4e2c9cb198cb8bf60d"
        "0x7d74c85df27fc42142ada6a238411727ee5572e0"
        "0x38126b14fb81c50b58a00ebfd8376f5e3de82438"
        "0xf5996dd3efc0ba3cf664209db59e441c34758de7"
        "0xa506565e7d1330f172ba41aaf90b840c47a0b822"
        "0xba60ec5b1c28993cba0e1c5022dc4c4735718873"
      ]
    }
  ) {
    user
    totalTrades
    netPnL
    volume
    usdcNetPnL
    usdcTotalTrades
    usdcTradesWon
    usdcVolume
    usdcWinRate
    # bfrNetPnL
    # bfrTotalTrades
    # bfrTradesWon
    # bfrVolume
    # bfrWinRate
    # arbNetPnL
    # arbTotalTrades
    # arbTradesWon
    # arbVolume
    # arbWinRate
  }
  winnerWinrate: weeklyLeaderboards(
    orderBy: winRate
    orderDirection: desc
    first: 100
    where: {
      timestamp: $timestamp
      totalTrades_gte: 5
      volume_gte: 100000000
      user_not_in: [
        "0x361e9013d7e4f2e4a035ba97fdb42cb7d2540259"
        "0x6fae0eed696ec28c81269b99240ee960570666f1"
        "0x0b8750c12fa14decd31eadff7e92cbd64a198094"
        "0x10df9a95010c8b9fbdc8f6191de824df9c99a8d8"
        "0x547a821c692921d82ebd936320dc1a608a6e38c1"
        "0x2a007f31146ff8f939b6ca3ad18c8d2a6e42eb73"
        "0xf0344cc4e0c0b5e653a83e4e2c9cb198cb8bf60d"
        "0x7d74c85df27fc42142ada6a238411727ee5572e0"
        "0x38126b14fb81c50b58a00ebfd8376f5e3de82438"
        "0xf5996dd3efc0ba3cf664209db59e441c34758de7"
        "0xa506565e7d1330f172ba41aaf90b840c47a0b822"
        "0xba60ec5b1c28993cba0e1c5022dc4c4735718873"
      ]
    }
  ) {
    user
    totalTrades
    netPnL
    volume
    winRate
    tradesWon
    usdcNetPnL
    usdcTotalTrades
    usdcTradesWon
    usdcVolume
    usdcWinRate
    # bfrNetPnL
    # bfrTotalTrades
    # bfrTradesWon
    # bfrVolume
    # bfrWinRate
    # arbNetPnL
    # arbTotalTrades
    # arbTradesWon
    # arbVolume
    # arbWinRate
  }
  totalData: weeklyLeaderboards(orderBy: netPnL, orderDirection: desc, first: 1000, where: { timestamp: $timestamp }) {
    totalTrades
    volume
  }
  reward: weeklyRevenueAndFees(where: { id: $timestampReward }) {
    settlementFee
    totalFee
  }
  userData: weeklyLeaderboards(where: { user: $address, timestamp: $timestamp }) {
    totalTrades
    netPnL
    volume
    user
    winRate
    tradesWon
    usdcNetPnL
    usdcTotalTrades
    usdcTradesWon
    usdcVolume
    usdcWinRate
    # bfrNetPnL
    # bfrTotalTrades
    # bfrTradesWon
    # bfrVolume
    # bfrWinRate
    # arbNetPnL
    # arbTotalTrades
    # arbTradesWon
    # arbVolume
    # arbWinRate
  }
}
