query ($timestamp: String!) {
  volumePerContracts(orderBy: timestamp, orderDirection: desc, first: 1000, where: { timestamp_gt: $timestamp }) {
    optionContract {
      address
    }
    amount
    settlementFee
    depositToken
  }
  optionContracts(where: { poolContract_not: null }) {
    configContract {
      address
      maxFee
      maxPeriod
      minFee
      minPeriod
      platformFee
      earlyCloseThreshold
      isEarlyCloseEnabled
      marketOIaddress
      IV
      poolOIaddress
      creationWindowAddress
    }
    address
    poolContract
    isPaused
    category
    asset
  }
}
