query ($prevDayEpoch: Int!) {
  totalStats: dashboardStat(id: "total") {
    totalSettlementFees
    totalTrades
    totalVolume
  }
  USDCstats: dashboardStat(id: "USDC") {
    totalSettlementFees
    totalTrades
    totalVolume
  }
  BFRstats: dashboardStat(id: "BFR") {
    totalSettlementFees
    totalTrades
    totalVolume
  }
  ARBstats: dashboardStat(id: "ARB") {
    totalSettlementFees
    totalTrades
    totalVolume
  }
  totalTraders: userStats(where: { period: total }) {
    uniqueCountCumulative
  }
  total24stats: volumePerContracts(
    orderBy: timestamp
    orderDirection: desc
    first: 1000
    where: { depositToken: "total", timestamp_gt: $prevDayEpoch }
  ) {
    amount
    settlementFee
  }
  USDC24stats: volumePerContracts(
    orderBy: timestamp
    orderDirection: desc
    first: 1000
    where: { optionContract_: { pool: "USDC" }, depositToken_not: "total", timestamp_gt: $prevDayEpoch }
  ) {
    amount
    settlementFee
  }
  BFR24stats: volumePerContracts(
    orderBy: timestamp
    orderDirection: desc
    first: 1000
    where: { optionContract_: { pool: "BFR" }, depositToken_not: "total", timestamp_gt: $prevDayEpoch }
  ) {
    amount
    settlementFee
  }
  ARB24stats: volumePerContracts(
    orderBy: timestamp
    orderDirection: desc
    first: 1000
    where: { optionContract_: { pool: "ARB" }, depositToken_not: "total", timestamp_gt: $prevDayEpoch }
  ) {
    amount
    settlementFee
  }
}
