query ($address: String!) {
  referralDatas(where: { id: $address }) {
    userTier
    referrer
    referrersWeeklyTimestamp
    referrersTradedWeekly
    referrersTraded
    referrersVolumeTradedWeekly
    totalRebateEarned
  }
}
