query ($address: String!, $timestampDaily: String!, $timestampWeekly: String!) {
  # ------------------
  # Win Rate: (count payout > 0) / total count
  # ------------------
  # Most Traded Assets: reduce array để find optionContract.asset nhiều nhất
  # ------------------
  # Metrics:
  # - TOKEN Trading Metrics:
  # + totalPayouts[tokenName] = SUM(payout)
  # + net_pnl[tokenName] = SUM(payout - totalFee)
  # + volume[tokenName] = SUM(totalFee)
  # ------------------
  userOptionDatas(first: 1000, where: { user: $address, state_not: 1 }) {
    optionContract {
      address
      token
      asset
    }
    amount
    payout
    totalFee
    expirationTime
  }
  # ------------------
  # Metrics:
  # - Referral:
  #
  # ------------------
  referralDatas(where: { id: $address }) {
    userTier
    referrers
    referrersWeeklyTimestamp
    referrersTradedWeekly
    referrersTraded
    referrersVolumeTradedWeekly
    totalTradesReferred
    totalVolumeOfReferredTrades
    totalRebateEarned
    totalTradingVolume
    totalDiscountAvailed
    totalTradesReferredUSDC
    totalVolumeOfReferredTradesUSDC
    totalRebateEarnedUSDC
    totalTradingVolumeUSDC
    totalDiscountAvailedUSDC
    totalTradesReferredETR
    totalVolumeOfReferredTradesETR
    totalRebateEarnedETR
    totalTradingVolumeETR
    totalDiscountAvailedETR
  }
  # ------------------
  # Interest:
  #
  # ------------------
  activeData: userOptionDatas(first: 1000, where: { user: $address, state: 1 }) {
    optionContract {
      address
      token
    }
    totalFee
  }
}
