node_env: development
cron: false

server:
  port: 8080
  host: 0.0.0.0
  url: http://localhost/
  web_url: http://localhost:8080

swagger:
  name: Backend API
  doc_url: /api/docs
  description: Backend
  version: 1.0
  is_auth: false
  username: root
  password: 123456

mongodb:
  uri: mongodb://localhost:27017/bo-be

encrypt:
  secretKey: 3a91efa0978bb7c90a8aad5020a7d0ab

jwt:
  secret: W53!ns!g&1P4
  access_expiration_minutes: 1440
  refresh_expiration_days: 30

i18n:
  fallback_language: en

ws:
  priceUpdate:
    url: wss://hermes.pyth.network/ws

network_supported: [8453, 84532]

blockchain:
  private_key:
    operator: ""
    sfPublisher: ""
  8453:
    provider: https://base.publicnode.com
    chain_id: 8453
    graphql:
      uri: ""
      burnedUri: ""
      mainnetDummyUri: ""
    contract:
      factory_v2:
        address: "0xFDa619b6d20975be80A10332cD39b9a4b0FAa8BB"
        blocknumber_creator: 0
      factory_v3:
        address: "0x38015D05f4fEC8AFe15D7cc0386a126574e8077B"
        blocknumber_creator: 0
      router:
        address: ""
        blocknumber_creator: 0
      register:
        address: ""
        blocknumber_creator: 0
      usdc:
        address: ""
        blocknumber_creator: 0
    pairContract:
      BTCUSD:
        address: ""
        blocknumber_creator: 0
  84532:
    provider: https://1rpc.io/base-goerli
    chain_id: 84532
    graphql:
      uri: ""
      burnedUri: ""
      mainnetDummyUri: ""
    contract:
      router:
        address: ""
        blocknumber_creator: 0
      register:
        address: ""
        blocknumber_creator: 0
      usdc:
        address: ""
        blocknumber_creator: 0
    pairContract:
      BTCUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
