node_env: development
cron: false

server:
  port: 8080
  host: 0.0.0.0
  url: http://localhost/
  web_url: http://localhost:8080

swagger:
  name: Backend API
  doc_url: /api/docs
  description: Backend
  version: 1.0
  is_auth: false
  username: root
  password: 123456

mongodb:
  uri: mongodb://localhost:27017/bo-be

encrypt:
  secretKey: 3a91efa0978bb7c90a8aad5020a7d0ab

jwt:
  secret: W53!ns!g&1P4
  access_expiration_minutes: 1440
  refresh_expiration_days: 30

i18n:
  fallback_language: en

ws:
  priceUpdate:
    url: wss://hermes.pyth.network/ws

network_supported: [84532]

blockchain:
  private_key:
    operator: ""
    sfPublisher: ""
    publisher: ""
  84532:
    provider: https://base-sepolia-rpc.publicnode.com
    chain_id: 84532
    graphql:
      uri:
      burnedUri:
      mainnetDummyUri:
    contract:
      router:
        address: ""
        blocknumber_creator: 0
      register:
        address: ""
        blocknumber_creator: 0
      usdc:
        address: ""
        blocknumber_creator: 0
      referral:
        address: ""
        blocknumber_creator: 0
    pairContract:
      BTCUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      ETHUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      LINKUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      TONUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      ARBUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      XRPUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      SOLUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      BNBUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      XAUUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      XAGUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      EURUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      GBPUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      WIFUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
      PEPEUSD:
        binaryOptions:
          address: ""
          blocknumber_creator: 0
        configOptions:
          address: ""
          blocknumber_creator: 0
list:
  rpcs: []
  operaters: []
